name: build and publish

on:
  push:
    branches: [main]

jobs:
  build-and-push-container-image:
    name: Container image
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      id: checkout
      uses: actions/checkout@v2

    - name: Setup qemu
      uses: docker/setup-qemu-action@v1

    - name: Setup buildx
      id: buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to ghcr
      id: ghcr-login
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push
      id: build-push
      uses: docker/build-push-action@v2
      with:
        platforms: linux/amd64,linux/arm64
        context: .
        tags: |
          ghcr.io/mgor/passtider:latest
        push: ${{ github.ref == 'refs/heads/main' }}

    - name: Image digest
      id: image-digest
      run: echo ${{ steps.build-push.outputs.digest }}

